GET http://localhost:3000/v1/siswa
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.bWF4aUBmaWxpYXNvZmlhLnNjaC5pZA.jmrZRZgWRCwEN0LZRo3cfg-TsKtiBvcnc3ymNs0dRvA
###

GET http://localhost:3000/v1/siswa?page=1&limit=1

###

POST http://localhost:3000/v1/siswa
Content-Type: application/json

{
    "nama": "Maxi Aditya Kusuma Winarjo",
    "email": "maxi@filiasofia.sch.id",
    "nohp": "+62895617047135",
    "jurusan": "IPA",
    "password": "javascript"
}

###

POST http://localhost:3000/v1/siswa/login
Content-Type: application/json

{
    "email": "maxi@filiasofia.sch.id",
    "password": "javascript"
}

###
PATCH http://localhost:3000/siswa
Content-Type: application/json

{
    "nama": "maxi aditya kusuma",
    "email": "maxiaditya123@gmail.com",
    "nohp": "+62895617047135",
    "jurusan": "IPS"
}

###
DELETE http://localhost:3000/v1/siswa/605f37d2c6f1722110ba5860