GET http://localhost:3000/v1/siswa

###

GET http://localhost:3000/v1/siswa?page=1&limit=1

###

POST http://localhost:3000/v1/siswa
Content-Type: application/json

{
    "nama": "Maxi Aditya Kusuma Winarjo",
    "email": "maxi@filiasofia.sch.id",
    "nohp": "+62895617047135",
    "jurusan": "IPA"
}
###
PATCH http://localhost:3000/siswa
Content-Type: application/json

{
    "nama": "maxi aditya kusuma",
    "email": "maxiaditya123@gmail.com",
    "nohp": "+62895617047135",
    "jurusan": "IPS"
}

###
DELETE http://localhost:3000/v1/siswa/604cb18e33d8190cb47c3771